name: fo_worker
dependencies:
- backports=1.0
- decorator=4.0.10
- entrypoints=0.2
- freetype=2.5.5
- get_terminal_size=1.0.0
- ipykernel=4.3.1
- ipython=4.2.0
- ipython_genutils=0.1.0
- ipywidgets=4.1.1
- jinja2=2.8
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.2.2
- jupyter_console=4.1.1
- jupyter_core=4.1.0
- libpng=1.6.22
- markupsafe=0.23
- mistune=0.7.2
- mkl=11.3.3
- nbconvert=4.2.0
- nbformat=4.0.1
- notebook=4.2.1
- numpy=1.11.0
- openssl=1.0.2h
- pandas=0.18.1
- path.py=8.2.1
- pexpect=4.0.1
- pickleshare=0.7.2
- pip=8.1.2
- ptyprocess=0.5.1
- pygments=2.1.3
- pyqt=4.11.4
- python=3.5.1
- python-dateutil=2.5.3
- pytz=2016.4
- pyzmq=15.2.0
- qt=4.8.7
- qtconsole=4.2.1
- readline=6.2
- setuptools=23.0.0
- simplegeneric=0.8.1
- sip=4.16.9
- six=1.10.0
- sqlite=3.13.0
- terminado=0.6
- tk=8.5.18
- tornado=4.3
- traitlets=4.2.1
- wheel=0.29.0
- xz=5.0.5
- zlib=1.2.8
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - pika==0.10.0
  - pulp==1.6.1
  - pymongo==3.3.0
  - pyparsing==2.1.5
  - scipy==0.18.1

